### ISSUE TITLE
opencourseware

### ISSUE THREAD

**Issue by duyguislakoglu** [kuisailab/ai-media-group#9]
**TODO**

- [x] E-mail template for the instructors

- [ ] YouTube playlist for each course

> - [ ] Panopto to YouTube

- [x] "Website", "Videos" sections for the following links:

> https://ai.ku.edu.tr/education/courses-and-educational-resources/courses-offered/
> https://ai.ku.edu.tr/education/programs/undergraduate-tracks/artificial-intelligence/ 

- [ ] "Assignments", "Previous Projects", "Exams" sections

- [ ] The Communication Office

**Comment by denizyuret** [comment]
I can help with Panopto -> Youtube instructions, I have done it before.

**Comment by duyguislakoglu** [comment]
Hocam we may need to re-upload your videos to [our channel](https://www.youtube.com/channel/UC3zQG-qRHF_Zl39c0kO5nZw).

And some courses are not accessible for all students. Can you give us a contact name?

**Comment by duyguislakoglu** [comment]
- [ ] We may need "categories" for this [page](https://ai.ku.edu.tr/education/courses-and-educational-resources/educational-resources/).
